---
achievements:
  achievements: {}
  permissions:
    manage_achievements: Award and remove achievements.
  shortcuts:
    achievements: achievement
  types:
    community: fa-users
    portal: fa-globe
    fs3: fa-dice-d20
    story: fa-book
    red_planet: fa-hat-cowboy
    comp: fa-heart
    serums: fa-syringe
    combat: fa-crosshairs