---
achievements:
  achievements: {}
  permissions:
    manage_achievements: Award and remove achievements.
  shortcuts:
    achievements: achievement
  types:
    community: fa-users
    portal: fa-globe
    fs3: fa-gamepad
    story: fa-book
    red_planet: fa-star
    comp: fa-heart
    serums: fa-medkit