---
fs3combat:
  damage_mods:
    HEAL: 0
    MILD: 0.25
    MAJOR: 2
    SEVERE: 4
    CRITICAL: 7
  damage_table:
    GRAZE: 0
    MILD: 30
    MAJOR: 65
    SEVERE: 95
  healing_cron:
    hour:
    - 7
    minute:
    - 47
  healing_points:
    HEAL: 0
    MILD: 7
    MAJOR: 7
    SEVERE: 10
    CRITICAL: 7
  pc_knockout_bonus: 1
