---
fs3combat:
  hitloc:
    Humanoid:
      areas:
        Chest:
        - Left Leg
        - Right Leg
        - Left Arm
        - Right Arm
        - Abdomen
        - Abdomen
        - Head
        - Chest
        - Chest
        - Chest
        Left Leg:
        - Chest
        - Right Foot
        - Right Leg
        - Right Leg
        - Abdomen
        - Abdomen
        - Left Foot
        - Left Leg
        - Left Leg
        - Left Leg
        Right Leg:
        - Chest
        - Left Foot
        - Left Leg
        - Left Leg
        - Abdomen
        - Abdomen
        - Right Foot
        - Right Leg
        - Right Leg
        - Right Leg
        Ass:
        - Abdomen
        - Abdomen
        - Abdomen
        - Left Leg
        - Right Leg
        - Left Leg
        - Right Leg
        - Ass
        - Ass
        - Ass
        Left Hand:
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Left Arm
        - Left Arm
        - Left Arm
        - Left Hand
        - Left Hand
        - Left Hand
        Right Hand:
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Right Arm
        - Right Arm
        - Right Arm
        - Right Hand
        - Right Hand
        - Right Hand
        Left Arm:
        - Head
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Left Hand
        - Left Hand
        - Left Arm
        - Left Arm
        - Left Arm
        Right Arm:
        - Head
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Right Hand
        - Right Hand
        - Right Arm
        - Right Arm
        - Right Arm
        Head:
        - Right Arm
        - Right Arm
        - Left Arm
        - Chest
        - Chest
        - Neck
        - Neck
        - Head
        - Head
        - Head
        Neck:
        - Right Arm
        - Right Arm
        - Left Arm
        - Chest
        - Chest
        - Head
        - Head
        - Neck
        - Neck
        - Neck
        Abdomen:
        - Left Leg
        - Right Leg
        - Left Leg
        - Right Leg
        - Chest
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Abdomen
      vital_areas:
      - Chest
      - Abdomen
      critical_areas:
      - Head
      - Neck
      - Ass
    GourdyPlant:
      areas:
        Gourd:
        - Left Vines
        - Left Vines
        - Flower
        - Flower
        - Right Vines
        - Right Vines
        - Gourd
        - Gourd
        - Gourd
        - Gourd
        Right Vines:
        - Right Vines
        - Left Vines
        - Left Vines
        - Flower
        - Flower
        - Gourd
        - Right Vines
        - Right Vines
        - Right Vines
        - Right Vines
        Left Vines:
        - Flower
        - Flower
        - Right Vines
        - Right Vines
        - Gourd
        - Left Vines
        - Left Vines
        - Left Vines
        - Left Vines
        - Left Vines
        Flower:
        - Left Vines
        - Left Vines
        - Left Vines
        - Right Vines
        - Right Vines
        - Gourd
        - Gourd
        - Flower
        - Flower
        - Flower
      vital_areas:
      - Gourd
      critical_areas: []
    Target:
      areas:
        Bullseye:
        - Ring 3
        - Ring 3
        - Ring 3
        - Ring 3
        - Ring 2
        - Ring 2
        - Ring 2
        - Ring 1
        - Ring 1
        - Bullseye
      vital_areas: []
      critical_areas: []
    Quadruped:
      areas:
        Chest:
        - Rear Left Leg
        - Rear Right Leg
        - Front Left Leg
        - Front Right Leg
        - Abdomen
        - Abdomen
        - Head
        - Chest
        - Chest
        - Chest
        Rear Left Leg:
        - Chest
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        Rear Right Leg:
        - Chest
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        - Abdomen
        - Abdomen
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        Groin:
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Right Leg
        - Rear Left Leg
        - Rear Right Leg
        - Groin
        - Groin
        - Groin
        Front Left Leg:
        - Head
        - Chest
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Front Left Leg
        - Front Left Leg
        - Front Left Leg
        - Front Left Leg
        Front Right Leg:
        - Head
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Abdomen
        - Front Right Leg
        - Front Right Leg
        - Front Right Leg
        - Front Right Leg
        Head:
        - Front Right Leg
        - Front Right Leg
        - Front Left Leg
        - Chest
        - Chest
        - Neck
        - Neck
        - Head
        - Head
        - Head
        Neck:
        - Front Right Leg
        - Front Right Leg
        - Front Left Leg
        - Chest
        - Chest
        - Head
        - Head
        - Neck
        - Neck
        - Neck
        Abdomen:
        - Rear Left Leg
        - Rear Right Leg
        - Rear Left Leg
        - Rear Right Leg
        - Chest
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Abdomen
      vital_areas:
      - Chest
      - Abdomen
      critical_areas:
      - Head
      - Neck
      - Groin
