---
fs3combat:
  armor:
    None:
      description: In case you need to take off armor
      defense: 0
      protection:
        Nowhere: 0
    Practical:
      description: Everyday, no-nonsense attire designed to offer protection from the usual dangers and inconveniences of life on the frontier.
      defense: 0
      protection:
        Head: 1
        Neck: 2
        Chest: 2
        Abdomen: 2
        Right Leg: 2
        Left Leg: 2
        Right Arm: 2
        Left Arm: 2
        Ass: 0
    Tactical:
      description: Military-Grade Kevlar Vest and Helmet
      defense: 0
      protection:
        Head: 7
        Neck: 5
        Chest: 8
        Abdomen: 7
    Police:
      description: Police-Grade Kevlar Vest
      defense: 0
      protection:
        Chest: 7
        Abdomen: 6
      allowed_specials:
      - Helmet
    Tank:
      description: Tank Armor
      defense: 0
      protection:
        Body: 22
        Engine: 22
        Weapon: 10
        Track: 15
        Side: 15
        Cabin: 22
    Apc:
      description: Light Armored Vehicle Armor
      defense: 0
      protection:
        Body: 12
        Engine: 12
        Weapon: 6
        Track: 8
        Side: 10
        Cabin: 12
    Truck:
      description: It's a truck
      defense: 0
      protection:
        Body: 7
        Cab: 6
        Engine: 8
    Aa Battery:
      description: Anti-Aircraft Battery
      defense: 0
      protection:
        Body: 7
        Controls: 7
        Weapon: 6
  armor specials:
    Helmet:
      description: A helmet
      protection:
        Head: 4
