---
fs3combat:
  weapons:
    Lasso:
      description: A looped rope thrown to entangle something.
      skill: Athletics
      lethality: 0
      penetration: 9
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Stun
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Dynamite:
      description: A thrown stick of dynamite.
      skill: Athletics
      lethality: 0
      penetration: 8
      weapon_type: Explosive
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Machete:
      description: Longer than a knife, meant for clearing brush, but can be an intimidating weapon in the right hands.
      skill: Melee
      lethality: 5
      penetration: 3
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Mine:
      description: Mine or other anti-personnel explosive
      skill: Demolitions
      lethality: 20
      penetration: 8
      weapon_type: Explosive
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Bow:
      description: A piece of wood with a string connecting the ends. Silent, compared to firearms.
      skill: Athletics
      lethality: 0
      penetration: 4
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Dynamite
    Rocket:
      description: Unguided Anti-Personnel Rocket
      skill: Gunnery
      lethality: 40
      penetration: 8
      weapon_type: Explosive
      is_automatic: false
      Ammo: 4
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Shaped Charge:
      description: Anti-Vehicle explosive
      skill: Demolitions
      lethality: 15
      penetration: 25
      weapon_type: Explosive
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Shrapnel:
      description: Random Shrapnel
      skill: 3
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Lmg:
      description: Light machinegun/SAW
      skill: Firearms
      lethality: 0
      penetration: 6
      weapon_type: Ranged
      is_automatic: true
      ammo: 100
      recoil: 4
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
      - Bipod
    Revolver:
      description: A basic six-shooter. 
      skill: Firearms
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      is_automatic: false
      ammo: 6
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
    Dual Revolvers:
      description: TWO basic six-shooters.
      skill: Firearms
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      is_automatic: false
      ammo: 12
      recoil: 0
      damage_type: Physical
      accuracy: -1
      has_shrapnel: false
      init_mod: 0
      dual_wield: true
      allowed_specials:
      - Ap
    Rifle:
      description: A long rifle. Bolt action.
      skill: Firearms
      lethality: 0
      penetration: 6
      weapon_type: Ranged
      is_automatic: false
      ammo: 5
      recoil: 3
      damage_type: Physical
      accuracy: 1
      has_shrapnel: false
      init_mod: -1
      allowed_specials:
      - Ap
      - Scope
    Repeater:
      description: A lever-action long gun that can shoot more rapidly than a rifle but with less power and accuracy.
      skill: Firearms
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      is_automatic: false
      ammo: 10
      recoil: 1
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
    Shotgun:
      description: Double-barreled shotgun
      skill: Firearms
      lethality: 10
      penetration: 3
      weapon_type: Ranged
      is_automatic: false
      ammo: 2
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Buckshot
    Club:
      description: Mace/club/baton
      skill: Melee
      lethality: -10
      penetration: 0
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Knife:
      description: Knife
      skill: Melee
      lethality: -5
      penetration: 4
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Throwing Axe:
      description: A thrown axe.
      skill: Athletics
      lethality: 0
      penetration: 3
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Unarmed:
      description: Unarmed
      skill: Melee
      lethality: -20
      penetration: 0
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Sparring
    Ecm:
      description: ECM Package
      skill: Gunnery
      lethality: 0
      penetration: 0
      weapon_type: Suppressive
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Hmg:
      description: Heavy machinegun.
      skill: Firearms
      lethality: 20
      penetration: 8
      weapon_type: Ranged
      is_automatic: true
      ammo: 100
      recoil: 6
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
      - Bipod
  weapon specials:
    Ap:
      description: Armor Piercing Rounds
      penetration: 2
    Bipod:
      description: Bipod Brace
      recoil: -3
    Scope:
      description: Sniper scope
      accuracy: 2
      init_mod: -1
    Buckshot:
      description: Shotgun pellets
      accuracy: 3
      penetration: -2
    Sparring:
      description: Padded sparring equipment
      lethality: -50
    Dynamite:
      description: A stick of dynamite tied to an arrow.
      has_shrapnel: true
