---
fs3combat:
  damage_mods:
    HEAL: 0
    MINOR: 0.25
    MAJOR: .5
    SEVERE: 1
    CRITICAL: 3
  damage_table:
    GRAZE: -150
    MINOR: 15
    MAJOR: 65
    SEVERE: 95
  healing_cron:
    hour:
    - 7
    minute:
    - 47
  healing_points:
    HEAL: 0
    MINOR: 7
    MAJOR: 7
    SEVERE: 10
    CRITICAL: 7
  pc_knockout_bonus: 2
