---
fs3combat:
  default_npc_type: 'Normal'
  npc_types:
    Trivial:
      Default: 4
      Firearms: 5
      Archery: 5
      Melee: 5
      Wounds: 20
    Easy:
      Default: 6
      Firearms: 7
      Archery: 7
      Melee: 7
      Wounds: 10
    Normal:
      Default: 8
      Archery: 9
      Firearms: 9
      Melee: 9
      Wounds: 0
    Hard:
      Default: 10
      Archery: 11
      Firearms: 11
      Melee: 11
      Wounds: -5
    Difficult:
      Default: 12
      Archery: 13
      Firearms: 13
      Melee: 13
      Wounds: -10
    Nightmare:
      Default: 14
      Archery: 15
      Firearms: 15
      Melee: 15
      Wounds: -15
    Impossible:
      Default: 22
      Archery: 24
      Firearms: 24
      Melee: 24
      Wounds: -25
