---
fs3combat:
  armor:
    None:
      description: In case you need to take off armor
      defense: 0
      protection:
        Nowhere: 0
    Practical:
      description: Everyday, no-nonsense attire designed to offer protection from the usual dangers and inconveniences of life on the frontier.
      defense: 0
      protection:
        Head: 1
        Neck: 2
        Chest: 2
        Abdomen: 2
        Right Leg: 2
        Left Leg: 2
        Right Arm: 2
        Left Arm: 2
        Ass: 0
    Tactical:
      description: Military-Grade Kevlar Vest and Helmet
      defense: 0
      protection:
        Head: 7
        Neck: 5
        Chest: 8
        Abdomen: 7
    NILE Armor:
      description: A system of overlapping ceramic plates and aramid fibers.
      is_hidden: true
      npc_only: true
      defense: 0
      protection:
        Head: 7
        Neck: 5
        Chest: 8
        Abdomen: 7
        Right Leg: 6
        Left Leg: 6
        Right Arm: 6
        Left Arm: 6
        Ass: 5
    Hide:
      description: Ordinary animal hide
      defense: 0
      npc_only: true
      protection:
        Chest: 4
        Rear Left Leg: 4
        Read Right Leg: 4
        Front Left Leg: 4
        Front Right Leg: 4
        Left Leg: 4
        Right Leg: 4
        Right Wing: 3
        Left Wing: 3
        Abdomen: 4
        Head: 3
        Left Head: 3
        Center Head: 3
        Right Head: 3
        Neck: 3
        Left Neck: 3
        Center Neck: 3
        Right Neck: 3
        Groin: 2
        Body: 4
        Fin: 2
        Tail: 4
        Leg: 4
        Arm: 4
        Body: 4
        Fin: 3
    Tough Hide:
      description: Thick, tough animal hide for critters that take a lickin' and keep on tickin'
      defense: 0
      npc_only: true
      protection:
        Chest: 6
        Rear Left Leg: 6
        Rear Right Leg: 6
        Front Left Leg: 6
        Front Right Leg: 6
        Left Leg: 6
        Right Leg: 6
        Tail: 6
        Right Wing: 6
        Left Wing: 6
        Abdomen: 6
        Head: 5
        Left Head: 5
        Center Head: 5
        Right Head: 5
        Neck: 4
        Left Neck: 4
        Center Neck: 4
        Right Neck: 4
        Groin: 4
        Leg: 5
        Arm: 5
        Body: 6
        Fin: 4
    Plant:
      description: Plant skin.
      defense: 0
      is_hidden: true
      npc_only: true
      protection:
        Left Vines: 3
        Right Vines: 3
        Stem: 3
        Gourd: 3
        Flower: 2
  armor specials:
    Helmet:
      description: A helmet
      protection:
        Head: 4
