---
fs3combat:
  damage_mods:
    HEAL: 0
    MINOR: 0.25
    MAJOR: 2
    SEVERE: 4
    CRITICAL: 7
  damage_table:
    GRAZE: -25
    MINOR: 0
    MAJOR: 50
    SEVERE: 95
  healing_cron:
    hour:
    - 7
    minute:
    - 47
  healing_points:
    HEAL: 0
    MINOR: 7
    MAJOR: 7
    SEVERE: 10
    CRITICAL: 7
  pc_knockout_bonus: 1
