---
fs3skills:
  action_skills:
  - name: Alertness
    desc: Noticing things and being aware of your surroundings.
    linked_attr: Perception
  - name: Athletics
    linked_attr: Brawn
    desc: General running, jumping, climbing, etc.
  - name: Archery
    linked_attr: Reflexes
    desc: Shooting bows.
  - name: Composure
    desc: Coolness under pressure.
    linked_attr: Grit
  - name: Demolitions
    desc: Blowing stuff up.
    linked_attr: Wits
  - name: Firearms
    desc: Shooting guns.
    specialties:
    - Rifles
    - Pistols
    linked_attr: Reflexes
  - name: Medicine
    desc: Tending to the ill and injured.
    linked_attr: Wits
  - name: Melee
    desc: Fighting with fists, knives, and hand-to-hand weapons.
    linked_attr: Brawn
  - name: Riding
    desc: Riding a HORSE.
    linked_attr: Reflexes
  - name: Persuasion
    desc: Winning people to your point of view.
    linked_attr: Presence
  - name: Stealth
    desc: Being sneaky.
    linked_attr: Reflexes
  - name: Technician
    desc: General mechanics/electronics and fixing things.
    linked_attr: Wits
  action_skills_blurb: 'Action Skills represent your ability in areas deemed important
    for gameplay.  Action Skills are rated from 0-8, but some games limit the highest
    and lowest ratings. See <a href="https://aresmush.com/fs3/fs3-3/chargen.html#action-skills"
    target="_blank">FS3: Action Skills</a> for details.'
