---
fs3skills:
  attributes:
  - name: Reflexes
    desc: Reflexes, dexterity, and hand-eye coordination.
  - name: Brawn
    desc: Physical strength and toughness.
  - name: Wits
    desc: Practical intelligence, inventiveness and creativity.
  - name: Grit
    desc: Willpower and determination.
  - name: Perception
    desc: Senses and general awareness.
  - name: Presence
    desc: Charisma and social intuition.
  attributes_blurb: 'Attributes represent basic abilities that everyone has to some
    extent. Attributes boost related skills, and come into play when no skill directly
    applies.  Attributes are rated from 1-4. See <a href="https://redplanetmu.com/wiki/guide:join_us#character-information"
    target="_blank">Join Us</a> and click on the Attributes tab for details.'
  default_linked_attr: Wits
