---
fs3skills:
  action_dots_beyond_chargen_max: 5
  allow_advantages_xp: false
  attr_dots_beyond_chargen_max: 2
  advantage_dots_beyond_chargen_max: 2
  days_between_learning: 0
  max_xp_hoard: 10
  periodic_xp: 2
  xp_costs:
    language:
      '1': 4
      '2': 12
    action:
      '1': 1
      '2': 3
      '3': 4
      '4': 7
      '5': 9
      '6': 11
      '7': 14
    background:
      '1': 4
      '2': 8
    attribute:
      '1': 1
      '2': 4
      '3': 9
    advantage:
      '1': 4
      '2': 12
  xp_cron:
    day_of_week:
    - Sat
    hour:
    - 21
    minute:
    - 0
