---
roles:
  default_roles:
  - everyone
  restricted_roles:
  - admin
  - coder
  admin_list_roles:
  - admin
  - storyteller
  - appstaff
  shortcuts:
    roles: role
    staff: admin
    role/add: role/assign
