---
serum:
  category: Other
  shortcuts:
    serums: serum
  Revitalizer:
    desc: "A healing concoction."
    duration: -1
    is_healing: true
    combat_only: false
    display_name: "%xw%X35Revitalizer Serum%xn"
  Adreno:
    desc: "This blend of ingredients will instantly revive anything from a dog to a horse. Too powerful to use on anything smaller."
    duration: -1
    is_revive: true
    combat_only: true
    display_name: "%x17%X14Adreno Serum%xn"
  Quickhand:
    desc: "Increases speed at the expense of caution."
    duration: 4
    init_mod: +2
    armor_mod: -3
    combat_only: true
    display_name: "%x9%X11Quickhand Serum%xn"
  Hardy:
    desc: "Increases the toughness of one's skin. Freaky. Slows you down."
    duration: 4
    init_mod: -2
    armor_mod: 3
    combat_only: true
    display_name: "%x223%X56Hardy Serum%xn"
  Glass Cannon:
    desc: "A danger to yourself and others"
    duration: 4
    lethality: 10
    lethality_mod: 10
    combat_only: true
    display_name: "%x22%X166Glass Cannon Serum%xn"
  serum_cron:
    minute:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55 
    - 56
    - 57
    - 58 
    - 59
  periodic_serum: "Revitalizer"