---
skin:
  header: "%x!+============================================================================+%xn"
  footer: "%x!+============================================================================+%xn"
  divider: "%x!------------------------------------------------------------------------------%xn"
  plain: "------------------------------------------------------------------------------"
  random_colors:
  - "%xr"
  line_with_text:
    default:
      color: "%x!"
      pattern: "-"
      text_position: 5
      left_bracket: "[ "
      right_bracket: " ]"
