---
who:
  where_style: scene
  who_fields:
  - field: status
    width: 7
    title: Status
  - field: lookingforrp
    width: 5
    title: RP?
  - field: name
    width: 20
    title: Name
  - field: group
    value: origin
    width: 16
    title: Origin
  - field: connected
    width: 7
    title: Conn
  - field: idle
    width: 4
    title: Idle
